changelog:
  categories:
    - title: Features
      labels:
        - feature
        - enhancement
        - feat
    - title: Fixes
      labels:
        - fix
        - bug
        - bugfix
    - title: Notable Changes
      labels:
        - notable
        - breaking-change
        - refactor
        - performance
    - title: Documentation
      labels:
        - docs
        - documentation
    - title: Maintenance
      labels:
        - chore
        - ci
        - dependencies
  exclude:
    labels:
      - skip-changelog
change-template: "- $TITLE by @$AUTHOR in #$NUMBER"
template: |
  ## What's Changed

  $CHANGES
